---
title: "Panel"
author: "陳柏銘"
date: "2018/6/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(magrittr)
```

```{r}
library(readr)
fatality <- read_csv("https://raw.githubusercontent.com/tpemartin/Econometric-Analysis/master/Part%20II/fatality.csv")
```

```{r}
#檢查資料，一次看全部的資料屬性
fatality %>% summarise_all(funs(class))
```

```{r}
library(plm)
```

```{r}
#串列內就是要設定（把誰）轉換成panel
fatality<-pdata.frame(fatality,c("state","year"))
# fatality %>% select(state)
```

```{r}
#各州啤酒稅（beertax）與車禍死亡率（mrall）
#In function formula. There it is used to inhibit the interpretation of operators such as "+", "-", "*" and "^" as formula operators, so they are used as arithmetical operators.


library(ggplot2)
fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000)))

#I() is to keep as the function is 
```

```{r}
#不同州，用不同顏色
fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000),color=state))
```

```{r}
#不同年，用不同顏色
fatality %>% 
  ggplot()+
  geom_point(aes(x=beertax,y=I(mrall*1000),color=year))
```

```{r}
#進行組內差異調整，做Demean
fatality %>% 
  group_by(state) %>% #依state分組進行以下程序：
  mutate(
    mrall_demean=mrall-mean(mrall),
    beertax_demean=beertax-mean(beertax)
    ) %>%
  select(mrall_demean,beertax_demean) %>%
  ungroup() -> demean_results # grouping variable會被保留，縱使看起來沒變化。
demean_results
```

```{r}
fatality %>% lm(data=., mrall~factor(state)) -> results
results$residuals
# results$residuals 也會是demean(mrall_mean)的結果
```

```{r}
#設定模型架構
model<-mrall~beertax
```

```{r}
#迴歸模型
#普通OLS model，用pooling的這個設定
pool1<-plm(model, data=fatality, model='pooling')
summary(pool1)
#你可以看到beertax的係數是正的。那這樣不太合理。
```

```{r}
re1<-plm(model, data=fatality, model='random')
summary(re1)
```

```{r}
#model = "within"，就是組內最小平方法。
#individual，就是一個固定效果模型（州），twoways，就是兩個固定效果模型
fe1<-plm(model, data=fatality, model='within', effect='individual')
summary(fe1)
```

```{r}
# effect = "twoways" allows to test for residual cross-sectional dependence after the introduction of
# time fixed effects to account for common shocks.
fe2<-plm(model, data=fatality, model='within', effect='twoways')
summary(fe2)
```

```{r}
library(stargazer)
stargazer(pool1,re1,fe1,fe2,type='text',
          column.labels = c("Pooled OLS","RE","FE-individual","FE-two-ways"))
```

```{r}
#Hausman test
#隨機效果模型中的，固定效果是否與解釋變數有關。
#H0 : 固定效果與（在控制變數下的解釋變數）獨立
#拒絕H0，代表兩者不獨立，也才需要相減去除他囉～
library(plm)
phtest(fe1,re1)
```

